name: Dispatch to Repo
on: 
  push:
    tags:
      - "*"
  workflow_dispatch:
    
jobs:
  dispatch:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        repo: ["ranjef420/repository.reef"]
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "ranjef420/skin.arcticfuse.2", "tag": "${{ github.ref_name }}"}'
